<a href="https://colab.research.google.com/github/Bits-Deep-Analytics/Predictive_analytics/blob/dev/Scripts/NBC.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open this notebook in Colaboratory"/></a>

### Read the dataset

In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_validate
from sklearn.naive_bayes import GaussianNB

In [2]:
data_url = 'https://raw.githubusercontent.com/Bits-Deep-Analytics/Predictive_analytics/dev/Data/Play_golf/Play_golf.csv'
dataset = read_csv(data_url)
# display(dataset)

### Preprocessing

In [7]:
lb = LabelEncoder() 
dataset['Outlook_'] = lb.fit_transform(dataset['Outlook'])
dataset['Temperature_'] = lb.fit_transform(dataset['Temperature']) 
dataset['Humidity_'] = lb.fit_transform(dataset['Humidity']) 
dataset['Windy_'] = lb.fit_transform(dataset['Windy'])   
dataset['Play_'] = lb.fit_transform(dataset['Play'])
X = pd.DataFrame(dataset.iloc[:,5:9])
Y = dataset.iloc[:,9]
display(dataset)

,Outlook,Temperature,Humidity,Windy,Play,Outlook_,Temperature_,Humidity_,Windy_,Play_
0,sunny,hot,high,False,no,2,1,0,0,0
1,sunny,hot,high,True,no,2,1,0,1,0
2,overcast,hot,high,False,yes,0,1,0,0,1
3,rainy,mild,high,False,yes,1,2,0,0,1
4,rainy,cool,normal,False,yes,1,0,1,0,1
5,rainy,cool,normal,True,no,1,0,1,1,0
6,overcast,cool,normal,True,yes,0,0,1,1,1
7,sunny,mild,high,False,no,2,2,0,0,0
8,sunny,cool,normal,False,yes,2,0,1,0,1
9,rainy,mild,normal,False,yes,1,2,1,0,1
10,sunny,mild,normal,True,yes,2,2,1,1,1
11,overcast,mild,high,True,yes,0,2,0,1,1
12,overcast,hot,normal,False,yes,0,1,1,0,1
13,rainy,mild,high,True,no,1,2,0,1,0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=1, random_state = 32)
# display(X_train, X_test, Y_train, Y_test)

In [11]:
naive_b = GaussianNB()
naive_b.fit(X_train, Y_train)
test_data = pd.concat([X_test, Y_test], axis=1)
test_data["prediction"] = naive_b.predict(X_test)
display(test_data)
print("Naive Bayes Accuracy:", naive_b.score(X_test,Y_test))
print(naive_b.predict_proba(X_test))

   Outlook_  Temperature_  Humidity_  Windy_  Play_  prediction
0         2             1          0       0      0           0

Naive Bayes Accuracy: 1.0
[[0.53009746 0.46990254]]

In [12]:
Y1 = ['rainy','cool','high',True]
Y1 = [[1, 0, 0, 1]]
prediction = naive_b.predict(Y1)
print(Y1,prediction)
print(naive_b.predict_proba(Y1))

[[1, 0, 0, 1]] [0]
[[0.67729032 0.32270968]]

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [13]:
display(dataset['Play_'].value_counts())
display(pd.crosstab(dataset['Outlook'],dataset['Play_'],normalize = 'columns'))
display(pd.crosstab(dataset['Temperature'],dataset['Play_'],normalize = 'columns'))
display(pd.crosstab(dataset['Humidity'],dataset['Play_'],normalize = 'columns'))
display(pd.crosstab(dataset['Windy'],dataset['Play_'],normalize = 'columns'))

1    9
0    5
Name: Play_, dtype: int64

Play_       0         1
Outlook
overcast  0.0  0.444444
rainy     0.4  0.333333
sunny     0.6  0.222222

Play_          0         1
Temperature
cool         0.2  0.333333
hot          0.4  0.222222
mild         0.4  0.444444

Play_       0         1
Humidity
high      0.8  0.333333
normal    0.2  0.666667

Play_    0         1
Windy
False  0.4  0.666667
True   0.6  0.333333

In [14]:
a = (0.33 * 0.33 * 0.333 * 0.3333 * (9/14))
b = (0.4 * 0.2 * 0.8 * 0.6 * (5/14))
print(a,b)
print(a/(a+b))
print(b/(a+b))

0.007770015777857143 0.013714285714285719
0.3616601536102422
0.6383398463897578